baseURL = 'http://www.GTM52.github.io/LaTeX-css/'
languageCode = 'en-us'
title = '$\LaTeX$.css'

[params]
	toc = true
	katex = true
	skin = 'auto'
	headerNav = [
		{ name = 'Tags', url = 'tags/' },
		{ name = 'Categories', url = 'categories/' },
		{ name = 'About', url = 'about/' },
	]